package com.example.AmazonTracker;

import org.jsoup.nodes.Document;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Date;
import org.springframework.ui.Model;
import org.jsoup.*;
import org.jsoup.nodes.*;
import java.io.File;
@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public String addNewUser (@RequestParam String url) {
        // @RequestParam means it is a parameter from the GET or POST request
        if(validateURL(url)) {//doesnt work
            return "redirect:/demo/greet";
        }
        String title = null;
        double price = -1;
        try {
            Document doc = Jsoup.connect(url).get();
            title = findTitle(doc, url);
            price = findPrice(doc, url);
            File logs = new File("logs.txt");
            FileWriter output = new FileWriter(logs,true);


            if(title == null || price == -1) {
                output.write(url);
                output.write(": title or price cannot be found\n");
                output.close();
                return "redirect:/demo/greet";
            }
        }
        catch(FileNotFoundException e) { //doc
            e.printStackTrace();
        }
        catch(IOException e) {
            e.printStackTrace();
        }
        User n = new User();
        n.setTitle("saved");
        n.setPrice(1);
        n.setUrl(url);
        n.setCreated_at(new Date());
        n.setUpdated_at(new Date());
        userRepository.save(n);
        return "redirect:/demo/greet";
    }
    @GetMapping(path="/greet")
    public String greeting(@RequestParam(name="name", required=false, defaultValue="World") String name, Model model) {
        model.addAttribute("name", name); //add this to templates
        return "demo"; //go to template name
    }
    //@Scheduled(fixedRate = 5000)
    public void scheduledWebCall() {
        System.out.println("hello world");
        //make the webscape call here after a fixed amount of time
    }
    public String findTitle(Document doc, String url){
        Element productTitle = doc.getElementById("productTitle");
        if(productTitle == null) {
            //try new method of finding product title, also if problem occurs then keep a log of it
            try {
                File logs = new File("logs.txt");
                FileWriter output = new FileWriter(logs,true);
                output.write(url);
                output.write(": Url is invalid\n");
                output.close();
            }
            catch(Exception e) {
                e.printStackTrace();
            }
            return null;
        }
        return productTitle.text();
    }
    public double findPrice(Document doc, String url)
    {
        return -1;
    }
    public boolean validateURL(String url) {
        if(!url.contains("amazon.com")) {//validate website, must be Amazon
            try {
                File logs = new File("logs.txt");
                FileWriter output = new FileWriter(logs,true);
                output.write(url);
                output.write(": Url is invalid\n");
                output.close();
            }
            catch(Exception e) {
                e.printStackTrace();
            }
            return true;
        }
        return false;
    }
}
